---
- name: Install ROS 2 Panda dependencies
  apt:
    name:
      - ros-humble-moveit-resources-panda-moveit-config
      - ros-humble-moveit-resources-panda-description
      - ros-humble-franka-description
    state: present
  become: true