---
galaxy_info:
  role_name: poetry_bash_ubuntu2204
  author: "internal"
  description: "Install Poetry and manage bash init files on Ubuntu 22.04"
  license: "proprietary"
  min_ansible_version: "2.13"
dependencies: []
