---
- name: Add MDT pre-defined models
  hosts: all
  become: false

  vars_files:
    - vars/mdt_vars.yml

  vars:
    model_home_dir: "{{ mdt_home_dir }}/models"

    mdt_dir: "{{ src_root_dir }}/mdt"
    mdt_apps_repo_url: "https://github.com/kwlee0220/mdt-apps.git"
    mdt_apps_project_dir: "{{ mdt_dir }}/mdt-apps"

  tasks:
    - name: Create MDT directory models
      file:
        path: "{{ model_home_dir }}"
        state: directory
        mode: '0755'

    - name: MDT 모델 등록 스크립트 복사
      copy:
        src: "files/add_models.sh"
        dest: "{{ model_home_dir }}/add_models.sh"
        mode: '0755'

    - name: Build 'mdt-apps' project with Gradle if necessary
      block:
      - name: Clone 'mdt-apps' repository
        git:
          repo: "{{ mdt_apps_repo_url }}"
          dest: "{{ mdt_apps_project_dir }}"
          version: master
          force: no
      - name: Build 'mdt-apps' project with Gradle
        shell: |
          cd {{ mdt_apps_project_dir }}
          gradle assemble
        args:
          executable: /bin/bash
      - name: Create symbolic link
        file:
          src: "{{ mdt_dir }}/mdt-apps/build/libs/mdt-apps-{{ mdt_build_version }}-all.jar"
          dest: "{{ mdt_home_dir }}/share/mdt-apps-all.jar"
          state: link

  roles:
    - role: postgresql_db
      vars:
        postgres_db: mdt_app
        postgres_user: "mdt"

- import_playbook: "models/deploy_test.yml"
- import_playbook: "models/deploy_Welder.yml"
- import_playbook: "models/deploy_innercase.yml"
# - import_playbook: "deploy_model_panda.yml"
